name: Go
on: [push]
jobs:
  test:
    # name: build
    strategy:
      matrix:
        go: [1.16.x, 1.17.x]
        os: [macOS-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # - name: Set up Go 1.13
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          # if [ -f Gopkg.toml ]; then
          #     curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          #     dep ensure
          # fi

      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v .
